grafana:
  serviceAccount:
    annotations:
      app: grafana
  defaultDashboardsEditable: "false"
  ## Timezone for the default dashboards
  ## Other options are: browser or a specific timezone, i.e. Europe/Luxembourg
  ##
  defaultDashboardsTimezone: America/Sao_Paulo
  adminPassword: admin

  # # To make Grafana persistent (Using Statefulset)
  # #
  nodeSelector: 
      kubernetes.io/hostname: worker1
  persistence:
    enabled: true
    type: pvc
    storageClassName: "local-storage"
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    selectorLabels:
      app.kubernetes.io/name: grafana

  serviceAccount:
    annotations:
      app: grafana

  ## Passed to grafana subchart and used by servicemonitor below
  ##
  service:
    annotations:
      ingress.kubernetes.io/service-upstream: "true"

prometheus:
  prometheusSpec:
    nodeSelector: 
      kubernetes.io/hostname: worker1
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus
    retention: "7d"
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      runAsGroup: 0
      fsGroup: 0
    ruleSelector: {}
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: 'istiod'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - istio-system
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: istiod;http-monitoring
      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: '.*-envoy-prom'